name: C compile

on: 
  push: 
    branches: [ "test" ] 
  pull_request:
    branches: [ "test" ] 
  
jobs: 
    build: 

      runs-on: debian-latest  

      steps: 
        - uses: actions/checkout@v4 
        - name: compiler install
          run: sudo apt install gcc
        - name: compile
          run: gcc 
          
