name: C compile

on: 
  push: 
    branches: [ "test" ] 
  pull_request:
    branches: [ "test" ] 
  
jobs: 
    build: 

      runs-on: ubuntu-latest  

      steps: 
        - uses: actions/checkout@v4 
        - name: compiler install
          run: sudo apt install gcc
        - name: compile
          run: gcc -Wall -Wextra -o Flashcard_thing Flashcard_thing-0.1.1.c
        - name: run program
          run: ./Flashcard_thing
        - name: echo num
          run: echo ("20")
        - name: echo file
          run: echo ("name.txt")
        - name: echo answ
          run: echo ("test succeed")
          
          
          
