name: C compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      permissions:
        contents: read
        pull-requests: read

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: compiler install
          run: sudo apt install gcc && sudo apt install valgrind
        - name: compile
          run: gcc -Wall -Wextra -Wpedantic Flashcard_thing-0.5.c -o Flashcard_thing
        - name: valgrind
          run: valgrind ./Flashcard_thing



